site_name: Material de ensino Octo IA

# Repository
repo_name: Octo-IA/Material-Conhecimento
repo_url: https://github.com/Octo-IA/Material-Conhecimento

# Copyright
copyright: Copyright &copy; 2016 - 2023 Martin Donath

theme:
  name: 'material'
  favicon: assets/logo/logo.png 
  logo: assets/logo/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes  
  # Mudar o tema da pagina
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      enabled: true
      repository: Octo-IA/Material-Conhecimento
      branch: main

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: G-SBN9GMV4K1
    feedback:
      title: Esta p치gina foi 칰til?
      ratings:
        - icon: material/heart
          name: Esta p치gina foi 칰til
          data: 1
          note: >-
            Obrigado pelo seu feedback!
        - icon: material/heart-broken
          name: Esta p치gina pode ser melhorada
          data: 0
          note: >-
            Obrigado pelo seu feedback! Ajude-nos a melhorar esta p치gina usando nosso 
            . <a href="https://forms.gle/v9UpZznvjUm56Ykv9" target="_blank" rel="noopener">formul치rio de feedback</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Octo-IA 

# Page tree
nav:
  - 游 Material:
    - material/introducao.md
  - 游꿢 Nosso Prop칩sito: index.md